// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9x_n7YfKQzkPGb5LwXWxzb_pIGP0VNc',
    appId: '1:1001558636852:web:981e51f2bf83efaf278d61',
    messagingSenderId: '1001558636852',
    projectId: 'todo-s-6badb',
    authDomain: 'todo-s-6badb.firebaseapp.com',
    storageBucket: 'todo-s-6badb.appspot.com',
    measurementId: 'G-RMYHL78WNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGE5F1H-68LTroLgmyPZhh66KPmRYQ2P8',
    appId: '1:1001558636852:android:d1a37ae15358a8db278d61',
    messagingSenderId: '1001558636852',
    projectId: 'todo-s-6badb',
    storageBucket: 'todo-s-6badb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQO3L4iEKpXV-qXTRD6hIYTqwNz8unrZo',
    appId: '1:1001558636852:ios:0511aedf57618c96278d61',
    messagingSenderId: '1001558636852',
    projectId: 'todo-s-6badb',
    storageBucket: 'todo-s-6badb.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQO3L4iEKpXV-qXTRD6hIYTqwNz8unrZo',
    appId: '1:1001558636852:ios:30912985f9130a52278d61',
    messagingSenderId: '1001558636852',
    projectId: 'todo-s-6badb',
    storageBucket: 'todo-s-6badb.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
